name: IO2-Main

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  Windows:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Get Deps (Boost, LuaJIT)
        shell: bash
        run: CI/get_win_deps.sh

      - name: Configure
        shell: bash
        run: LUA_DIR=.\LuaJIT\ cmake .

      - name: Build
        run: cmake --build .
