name: IO2-Main

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches: [ master ]
  workflow-dispatch:


jobs:
  Windows:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Get Deps (Boost, LuaJIT)
        shell: bash
        run: get-deps.sh

      - name: Configure
        run: cmake .

      - name: Build
        run: cmake --build .
