name: IO2-Main

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  Windows:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Cache Boost
        id: cache-LuaBoost
        uses: actions/cache@v3
        with:
          path: |
            C:/local/boost_1_80_0/
            D:/a/Lua-io2/Lua-io2/LuaJIT/
            D:/a/Lua-io2/Lua-io2/sol2/
          key: ${{ runner.os }}-LuaBoost

      - name: Get Deps (Boost, LuaJIT)
        shell: bash
        if: steps.cache-LuaBoost.outputs.cache-hit != 'true'
        run: CI/get_win_deps.sh

      - name: Configure
        shell: bash
        run: LUA_DIR=LuaJIT/ cmake .

      - name: Build
        run: cmake --build .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Stable-${{ github.ref }}
          release_name: Release-CI
          body: |
            CI Build for Dreamweave IO2 fork
          draft: false
          prerelease: false

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: D:\a\Lua-io2\Lua-io2\Debug\io2.dll
